# Introduction
In this Part, we will prepare our data for machine learning in Part IV. 

The interesting thing about the data is that the categorical values are engineered from the numerical ones. 

For example:
- Friends (Willingness to seek help from friends when students encounter emotional difficulties)
- Friends_bi (Whether students are willing to seek help from friends when they encounter emotional difficulties)

As such, our approach for this dataset is slightly different. We will first:
1. Get a DataFrame that contains only numerical columns
2. Get a DataFrame that contains only dummified variables from categorical variables
3. A combination of both numerical and dummified variables

### Step 1: Import pandas
First step, let's import pandas so we can read the DataFrame that we got at the end of Part I.

In [1]:
# Step 1: Import pandas
import pandas as pd

### Step 2: Read the cleaned CSV from Part I
Read the CSV from Part I. You should have 268 rows and 50 columns.

In [4]:
# Step 2: Read the cleaned CSV
df = pd.read_csv("part1_data.csv")
df

    inter_dom Region  Gender  ... Alone_bi  Others_bi  Internet_bi
0       Inter    SEA    Male  ...       No         No           No
1       Inter    SEA    Male  ...       No         No           No
2       Inter    SEA    Male  ...       No         No           No
3       Inter     EA  Female  ...       No         No           No
4       Inter     EA  Female  ...       No         No           No
..        ...    ...     ...  ...      ...        ...          ...
263       Dom    JAP  Female  ...       No         No          Yes
264       Dom    JAP  Female  ...       No         No           No
265       Dom    JAP  Female  ...       No         No           No
266       Dom    JAP    Male  ...       No         No           No
267       Dom    JAP    Male  ...      Yes         No           No

[268 rows x 50 columns]

### Step 3: Get DataFrame containing numerical columns only
Sounds familiar? We're repeating Part II Step 4a - selecting columns that contain float64 only.

We expect a DataFrame with 268 rows and 26 columns.

In [3]:
# Step 3: Get a DataFrame containing only numbers
df_float = df.select_dtypes(include = ["float64"])
df_float

      Age  Age_cate  Stay  Japanese  ...  Reli  Alone  Others  Internet
0    24.0       4.0   5.0       3.0  ...   1.0    3.0     4.0       3.0
1    28.0       5.0   1.0       4.0  ...   1.0    1.0     1.0       3.0
2    25.0       4.0   6.0       4.0  ...   1.0    1.0     1.0       3.0
3    29.0       5.0   1.0       2.0  ...   2.0    4.0     4.0       3.0
4    28.0       5.0   1.0       1.0  ...   5.0    4.0     4.0       3.0
..    ...       ...   ...       ...  ...   ...    ...     ...       ...
263  21.0       3.0   4.0       5.0  ...   1.0    1.0     1.0       6.0
264  22.0       3.0   3.0       3.0  ...   2.0    2.0     1.0       3.0
265  19.0       2.0   1.0       5.0  ...   1.0    1.0     1.0       2.0
266  19.0       2.0   1.0       5.0  ...   4.0    4.0     4.0       2.0
267  20.0       2.0   2.0       5.0  ...   4.0    6.0     1.0       3.0

[268 rows x 26 columns]

### Step 4: Export the numerical DataFrame as CSV
We'll be using this CSV later in Part IV.

In [5]:
# Step 4: Export the numerical DataFrame as CSV
df_float.to_csv("part3_numerical_data.csv", index = False)

### Step 5: Get DataFrame containing categorical columns only
Now that we're done with numerical, let's tackle categorical values. 

Get a DataFrame that contains only categorical values.

In [9]:
# Step 5: Get a DataFrame that contains only strings
df_object = df.select_dtypes(include = ["object"])
df_object

    inter_dom Region  Gender  ... Alone_bi Others_bi Internet_bi
0       Inter    SEA    Male  ...       No        No          No
1       Inter    SEA    Male  ...       No        No          No
2       Inter    SEA    Male  ...       No        No          No
3       Inter     EA  Female  ...       No        No          No
4       Inter     EA  Female  ...       No        No          No
..        ...    ...     ...  ...      ...       ...         ...
263       Dom    JAP  Female  ...       No        No         Yes
264       Dom    JAP  Female  ...       No        No          No
265       Dom    JAP  Female  ...       No        No          No
266       Dom    JAP    Male  ...       No        No          No
267       Dom    JAP    Male  ...      Yes        No          No

[268 rows x 24 columns]

### Step 6: Dummify the entire categorical DataFrame
Now that we have the DataFrame, let's dummify the values to turn the categories into binary features. 

![OnehotEncodingExample.png](attachment:OnehotEncodingExample.png)

We can use pandas .get_dummies method to turn a column, or columns, into dummies. 

<strong>Make sure that you drop first column to avoid redundancies.</strong>

We expect a resulting DataFrame that is 
- 268 rows
- 34 columns

![DummyDropFirst.png](attachment:DummyDropFirst.png)

<strong>Hint: Make sure your drop_first parameter is true to avoid redundant dummy columns.</strong>

In [11]:
# Step 6: Dummify your categorical DataFrame
df_dummy = pd.get_dummies(df_object, drop_first = True)
df_dummy

     inter_dom_Inter  Region_JAP  ...  Others_bi_Yes  Internet_bi_Yes
0                  1           0  ...              0                0
1                  1           0  ...              0                0
2                  1           0  ...              0                0
3                  1           0  ...              0                0
4                  1           0  ...              0                0
..               ...         ...  ...            ...              ...
263                0           1  ...              0                1
264                0           1  ...              0                0
265                0           1  ...              0                0
266                0           1  ...              0                0
267                0           1  ...              0                0

[268 rows x 34 columns]

### Step 7: Export the dummified DataFrame as CSV
Export this DataFrame as well as a CSV for use in Part IV.

In [12]:
# Step 7: Export the DataFrame from Step 6
df_dummy.to_csv("part3_dummy_data.csv", index = False)

### Step 8: Get a DataFrame that is both numerical and dummified
Now that we have a numerical DataFrame, and a dummified DataFrame, let's get a DataFrame that contains both. 

There are two ways to do this:
1. Use .get_dummies on your original DataFrame (don't forget to drop the first column)
2. Concatenate the two DataFrames from Step 3 and 6

Both steps lead to the same DataFrame, so it's fine whichever you pursue. Method 1 is simpler and Method 2 lets you train your DataFrame combination skills. 

At the end, you will have a DataFrame that has:
- 268 rows
- 60 columns

In [14]:
# Step 8: Get the full dummified DataFrame
df_full_dummy = pd.get_dummies(df, drop_first = True)
df_full_dummy

      Age  Age_cate  Stay  ...  Alone_bi_Yes  Others_bi_Yes  Internet_bi_Yes
0    24.0       4.0   5.0  ...             0              0                0
1    28.0       5.0   1.0  ...             0              0                0
2    25.0       4.0   6.0  ...             0              0                0
3    29.0       5.0   1.0  ...             0              0                0
4    28.0       5.0   1.0  ...             0              0                0
..    ...       ...   ...  ...           ...            ...              ...
263  21.0       3.0   4.0  ...             0              0                1
264  22.0       3.0   3.0  ...             0              0                0
265  19.0       2.0   1.0  ...             0              0                0
266  19.0       2.0   1.0  ...             0              0                0
267  20.0       2.0   2.0  ...             1              0                0

[268 rows x 60 columns]

### Step 9: Export the final DataFrame as CSV
Now that you've the DataFrame, time to export this as our third CSV.

In [15]:
# Step 9: Export the third DataFrame as a CSV
df_full_dummy.to_csv("part3_full_dummy_data.csv", index = False)

### End of Part III
This dataset is unique in the sense that the features were sort of engineered already for us.

As such, we just needed to split the DataFrame into different parts. 

More specifically, we prepared three sets of DataFrames so that we can work with them in the next Part, which is machine learning modelling.